Updated hystrix version. Copying MDC Context from parent thread
santanusinha/hystrix-function-wrapper pull request #3
Opened 2019-01-12 16:23 UTC by r0goyal

2019-01-14 08:32 UTC, santanusinha requested changes

2019-01-14 08:32 UTC, santanusinha commented on src/main/java/io/appform/core/hystrix/GenericHystrixCommand.java
> +        parentThreadContext = MDC.getCopyOfContextMap();
Context can be pulled just before CHECK HERE

2019-01-14 08:32 UTC, santanusinha commented on src/main/java/io/appform/core/hystrix/GenericHystrixCommand.java
>          return new HystrixCommand<ReturnType>(setter) {
CHECK HERE

2019-01-14 08:32 UTC, santanusinha commented on src/test/java/io/appform/core/hystrix/CommandFactoryTest.java
> +import com.netflix.hystrix.HystrixCommandKey;
Remove

2019-01-14 08:48 UTC, santanusinha approved these changes

2019-01-14 08:48 UTC, merged

2020-01-28 05:30 UTC, Thrigunesh commented on src/main/java/io/appform/core/hystrix/GenericHystrixCommand.java
> -                    MDC.remove(TRACE_ID);
@r0goyal Any specific reason to clear mdc?